#!/bin/bash
set -euo pipefail
TMPDIR=${TMPDIR:-/tmp}

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

logs=/opt/resource/logs/check.log
touch $logs

payload=$TMPDIR/echo-request
cat > "$payload" <&0

targetUrl=$(jq -r '.source.base_url' "$payload")
jqFilter=$(jq -r '.source.jq_filter' "$payload")
debug=$(jq -r '.source.debug // false' "$payload")

optionalArguments=()
if [[ "$debug" == true ]]; then
  set -x
  optionalArguments+=("-S")
fi

unencodedCredentials="$(jq -r '.source.credentials // ""' "$payload")"
if [[ -n "$unencodedCredentials" ]]; then
  optionalArguments+=("--header=\"Authorization: Basic $(echo -n "$unencodedCredentials" | base64)\"")
fi

mapfile -t headers < <(jq -r '(.source.headers // [])[]' "$payload")
for header in "${headers[@]}"; do
  optionalArguments+=("--header=${header}")
done

response=$TMPDIR/echo-response

wget "${optionalArguments[@]}" \
     --header='Accept: application/json' \
     -O "$response" "$targetUrl"

versions=$(jq -r "$jqFilter" "$response" | jq -Ms)

echo "$versions" >> $logs
echo "$versions" >&3
