#!/bin/bash
set -e
TMPDIR=${TMPDIR:-/tmp}

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

mkdir -p $destination

payload=$TMPDIR/echo-request
cat > $payload <&0

version=$(jq -r '.version // ""' < $payload)

echo $version > $destination/version

echo '{ "version" : {}, "metadata": []  }' >&3
